require 'rubygems'
require 'extensions/all'
require 'dev-utils/debug'
require 'ruby-debug'
require 'redcloth'

require 'moodle_markup/01_support'
require 'moodle_markup/02_options_dirs_lines'
require 'moodle_markup/03_resource_and_website'
require 'moodle_markup/04_topic_document'
require 'moodle_markup/05_parser_and_filter'
